// This file is auto-generated by `php artisan stimulus:install`
// Run that command whenever you add a new controller or create them with
// `php artisan stimulus:make controllerName`

import { Stimulus } from '../libs/stimulus'


import DropdownController from './dropdown_controller'
Stimulus.register('dropdown', DropdownController)

import HelloController from './hello_controller'
Stimulus.register('hello', HelloController)

import ThemeController from './theme_controller'
Stimulus.register('theme', ThemeController)